# Настройка редиректов для прокси
[[redirects]]
  from = "/api/*"
  to = "https://production-project-server-sepia-sigma.vercel.app/:splat"
  status = 200
  force = true

# Настройка редиректов для обработки SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
